name: My Github Workflow
on:
    push:
        branches:
            - main

env:
    PROJECT_NAME: github-actions-demo
    COURSE: LLMOPS-AI-Learning            

jobs:
    myexamplejob:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Checkout the repo"
            - name: Checkout Repo
              uses: actions/checkout@v4
            - run: printenv
            - run: echo "This is the env ${{ env.PROJECT_NAME }} and ${{ env.COURSE }}"
            